vich_uploader:
    db_driver: orm
    mappings:
        animal_image:
            uri_prefix: /uploads/animals
            upload_destination: '%kernel.project_dir%/public/uploads/animals'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        habitat_image:
            uri_prefix: /uploads/habitats
            upload_destination: '%kernel.project_dir%/public/uploads/habitats'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true